import type { Place } from "./types";

/*
  Datos de MUESTRA para desarrollo y demo. Permiten correr la app sin Supabase.
  Coordenadas aproximadas — los datos reales llegan con el sembrado
  (scripts/seed-google-places.ts). Cuando hay credenciales de Supabase,
  lib/queries.ts consulta la base y NO usa este archivo.
*/
export const SAMPLE_PLACES: Place[] = [
  // ── Bibliotecas (sistema público) ─────────────────────────────
  {
    id: "s-biblioteca-espana",
    type: "biblioteca",
    name: "Parque Biblioteca España",
    slug: "parque-biblioteca-espana",
    description:
      "Emblemático parque biblioteca en Santo Domingo Savio, ícono arquitectónico de la ciudad.",
    address: "Cra. 33B #107A-100",
    neighborhood: "Santo Domingo Savio",
    municipality: "Medellín",
    lat: 6.2967,
    lng: -75.5417,
    hours: "Mar–Sáb 8:00–18:00",
    isFree: true,
    services: ["wifi", "salas de estudio", "préstamo", "eventos", "ludoteca"],
    entity: "Sistema de Bibliotecas Públicas de Medellín",
  },
  {
    id: "s-biblioteca-leon-de-greiff",
    type: "biblioteca",
    name: "Parque Biblioteca León de Greiff (La Ladera)",
    slug: "parque-biblioteca-leon-de-greiff",
    address: "Cl. 59 #36-30",
    neighborhood: "La Ladera",
    municipality: "Medellín",
    lat: 6.2445,
    lng: -75.5493,
    hours: "Mar–Sáb 8:00–18:00",
    isFree: true,
    services: ["wifi", "salas de estudio", "préstamo", "eventos"],
    entity: "Sistema de Bibliotecas Públicas de Medellín",
  },
  {
    id: "s-biblioteca-belen",
    type: "biblioteca",
    name: "Parque Biblioteca Belén",
    slug: "parque-biblioteca-belen",
    address: "Cra. 76 #18A-19",
    neighborhood: "Belén",
    municipality: "Medellín",
    lat: 6.2318,
    lng: -75.6055,
    hours: "Mar–Sáb 8:00–18:00",
    isFree: true,
    services: ["wifi", "salas de estudio", "préstamo", "ludoteca"],
    entity: "Sistema de Bibliotecas Públicas de Medellín",
  },
  {
    id: "s-biblioteca-san-javier",
    type: "biblioteca",
    name: "Parque Biblioteca San Javier",
    slug: "parque-biblioteca-san-javier",
    address: "Cl. 39B #97-50",
    neighborhood: "San Javier",
    municipality: "Medellín",
    lat: 6.2807,
    lng: -75.6136,
    hours: "Mar–Sáb 8:00–18:00",
    isFree: true,
    services: ["wifi", "préstamo", "eventos"],
    entity: "Sistema de Bibliotecas Públicas de Medellín",
  },
  {
    id: "s-biblioteca-piloto",
    type: "biblioteca",
    name: "Biblioteca Pública Piloto",
    slug: "biblioteca-publica-piloto",
    description:
      "Una de las bibliotecas más importantes de la ciudad, con el Archivo Fotográfico patrimonial.",
    address: "Cra. 64 #50-32",
    neighborhood: "Carlos E. Restrepo",
    municipality: "Medellín",
    lat: 6.2568,
    lng: -75.5773,
    hours: "Lun–Vie 8:00–18:00 · Sáb 9:00–16:00",
    isFree: true,
    services: ["wifi", "salas de estudio", "préstamo", "archivo"],
    entity: "Biblioteca Pública Piloto",
  },
  {
    id: "s-biblioteca-epm",
    type: "biblioteca",
    name: "Biblioteca EPM",
    slug: "biblioteca-epm",
    address: "Cra. 54 #44-48, Plaza de las Luces",
    neighborhood: "La Candelaria",
    municipality: "Medellín",
    lat: 6.251,
    lng: -75.5686,
    hours: "Mar–Sáb 8:30–17:30",
    website: "https://www.fundacionepm.org.co/biblioteca-epm",
    instagram: "bibliotecaepm",
    isFree: true,
    services: ["wifi", "salas de estudio", "préstamo", "eventos"],
    entity: "Fundación EPM",
  },
  // ── Librerías ────────────────────────────────────────────────
  {
    id: "s-libreria-grammata",
    type: "libreria",
    name: "Librería Grámmata",
    slug: "libreria-grammata",
    description: "Librería independiente con curaduría cuidada y agenda cultural.",
    address: "El Poblado",
    neighborhood: "El Poblado",
    municipality: "Medellín",
    lat: 6.2088,
    lng: -75.5665,
    hours: "Lun–Sáb 10:00–19:00",
    website: "https://libreriagrammata.com",
    instagram: "libreriagrammata",
    specialties: ["nuevos", "independiente", "café-librería"],
  },
  {
    id: "s-libreria-al-pie-de-la-letra",
    type: "libreria",
    name: "Al Pie de la Letra",
    slug: "al-pie-de-la-letra",
    address: "Laureles",
    neighborhood: "Laureles",
    municipality: "Medellín",
    lat: 6.245,
    lng: -75.592,
    hours: "Lun–Sáb 10:00–19:00",
    instagram: "alpiedelaletra.co",
    specialties: ["nuevos", "usados", "independiente"],
  },
  {
    id: "s-libreria-palinuro",
    type: "libreria",
    name: "Librería Palinuro",
    slug: "libreria-palinuro",
    address: "Centro",
    neighborhood: "La Candelaria",
    municipality: "Medellín",
    lat: 6.2486,
    lng: -75.5686,
    hours: "Lun–Sáb 9:00–18:00",
    specialties: ["usados", "académico"],
  },
  {
    id: "s-libreria-cientifica",
    type: "libreria",
    name: "Librería Científica",
    slug: "libreria-cientifica",
    address: "Centro",
    neighborhood: "La Candelaria",
    municipality: "Medellín",
    lat: 6.2503,
    lng: -75.5665,
    hours: "Lun–Vie 9:00–18:00 · Sáb 9:00–13:00",
    specialties: ["académico", "nuevos"],
  },
  {
    id: "s-libreria-acentos",
    type: "libreria",
    name: "Librería Acentos",
    slug: "libreria-acentos",
    address: "Envigado",
    neighborhood: "Centro",
    municipality: "Envigado",
    lat: 6.1667,
    lng: -75.5836,
    hours: "Lun–Sáb 10:00–19:00",
    specialties: ["independiente", "infantil", "nuevos"],
  },
  {
    id: "s-libreria-la-anticuaria",
    type: "libreria",
    name: "La Anticuaria Libros",
    slug: "la-anticuaria-libros",
    description: "Libros usados, raros y de segunda mano.",
    address: "Sabaneta",
    neighborhood: "Centro",
    municipality: "Sabaneta",
    lat: 6.1518,
    lng: -75.6167,
    hours: "Lun–Sáb 10:00–18:00",
    specialties: ["usados", "raros"],
  },
];
